"""Initial migration with all 13 tables and master data

Revision ID: 4a6d62a01f61
Revises: 
Create Date: 2026-04-21 12:32:54.828015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a6d62a01f61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('rgb', sa.String(length=20), nullable=True),
    sa.Column('hsl', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_avatar_colors_display_order'), 'avatar_colors', ['display_order'], unique=False)
    op.create_index(op.f('ix_avatar_colors_hex_code'), 'avatar_colors', ['hex_code'], unique=True)
    op.create_index(op.f('ix_avatar_colors_is_active'), 'avatar_colors', ['is_active'], unique=False)
    op.create_table('avatar_styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('svg_template', sa.Text(), nullable=False),
    sa.Column('animation_type', sa.String(length=50), nullable=False),
    sa.Column('animation_duration', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('color_customizable', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_avatar_styles_animation_type', 'avatar_styles', ['animation_type'], unique=False)
    op.create_index(op.f('ix_avatar_styles_display_order'), 'avatar_styles', ['display_order'], unique=False)
    op.create_index(op.f('ix_avatar_styles_is_active'), 'avatar_styles', ['is_active'], unique=False)
    op.create_index(op.f('ix_avatar_styles_slug'), 'avatar_styles', ['slug'], unique=True)
    op.create_table('color_palette',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('palette_type', sa.Enum('SUBJECT', 'NOTE', 'BOTH', name='palettetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_color_palette_is_active'), 'color_palette', ['is_active'], unique=False)
    op.create_table('tint_palette',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hsl', sa.String(length=50), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tint_palette_category'), 'tint_palette', ['category'], unique=False)
    op.create_index(op.f('ix_tint_palette_display_order'), 'tint_palette', ['display_order'], unique=False)
    op.create_index(op.f('ix_tint_palette_is_active'), 'tint_palette', ['is_active'], unique=False)
    op.create_table('palette_colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('palette_id', sa.UUID(), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('hsl', sa.String(length=50), nullable=True),
    sa.Column('color_name', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['palette_id'], ['color_palette.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_palette_colors_palette_id', 'palette_colors', ['palette_id'], unique=False)
    op.create_index('ix_palette_colors_palette_id_display_order', 'palette_colors', ['palette_id', 'display_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_style_id', sa.UUID(), nullable=False),
    sa.Column('avatar_color_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_color_id'], ['avatar_colors.id'], ),
    sa.ForeignKeyConstraint(['avatar_style_id'], ['avatar_styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['palette_colors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_index('ix_subjects_user_id_name', 'subjects', ['user_id', 'name'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_storage_key'), 'materials', ['storage_key'], unique=True)
    op.create_index(op.f('ix_materials_subject_id'), 'materials', ['subject_id'], unique=False)
    op.create_index('ix_materials_subject_id_created_at', 'materials', ['subject_id', 'created_at'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'REVISING', 'COMPLETED', name='topicstatus'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('tint_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 5', name='confidence_range_check'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tint_id'], ['tint_palette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_status'), 'topics', ['status'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_index('ix_topics_subject_id_name', 'topics', ['subject_id', 'name'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tint_id', sa.UUID(), nullable=False),
    sa.Column('scribbles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tint_id'], ['tint_palette.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_topic_id'), 'notes', ['topic_id'], unique=False)
    op.create_index('ix_notes_topic_id_created_at', 'notes', ['topic_id', 'created_at'], unique=False)
    op.create_table('playground_snippets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_snippets_note_id'), 'playground_snippets', ['note_id'], unique=False)
    op.create_index(op.f('ix_playground_snippets_user_id'), 'playground_snippets', ['user_id'], unique=False)
    op.create_index('ix_playground_snippets_user_id_created_at', 'playground_snippets', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    
    # Seed master data
    seed_master_data(op)


def seed_master_data(op):
    """Seed master data for avatar styles, colors, and tints."""
    from uuid import uuid4
    from datetime import datetime
    from sqlalchemy import text
    
    now = datetime.utcnow()
    
    # Seed avatar styles
    avatar_styles_sql = """
    INSERT INTO avatar_styles (id, name, slug, description, svg_template, animation_type, animation_duration, color_customizable, display_order, is_active, created_at)
    VALUES 
        (:id1, 'Floating Orb', 'floating-orb', 'Smooth floating sphere with gradient', '<svg></svg>', 'float', 4.0, true, 1, true, :now),
        (:id2, 'Bouncing Ball', 'bouncing-ball', 'Playful bouncing sphere', '<svg></svg>', 'bounce', 1.5, true, 2, true, :now),
        (:id3, 'Rotating Cube', 'rotating-cube', '3D rotating cube with perspective', '<svg></svg>', 'rotate', 6.0, true, 3, true, :now),
        (:id4, 'Pulsing Star', 'pulsing-star', 'Star that pulses with light', '<svg></svg>', 'pulse', 2.0, true, 4, true, :now),
        (:id5, 'Wave Motion', 'wave-motion', 'Wavy liquid-like motion', '<svg></svg>', 'wave', 3.5, true, 5, true, :now),
        (:id6, 'Spinning Ring', 'spinning-ring', 'Concentric spinning rings', '<svg></svg>', 'rotate', 4.0, true, 6, true, :now),
        (:id7, 'Morphing Shape', 'morphing-shape', 'Shape that morphs between forms', '<svg></svg>', 'morph', 5.0, true, 7, true, :now),
        (:id8, 'Glowing Particle', 'glowing-particle', 'Glowing particles with trail effect', '<svg></svg>', 'particle', 3.0, true, 8, true, :now)
    """
    
    op.execute(text(avatar_styles_sql).bindparams(
        id1=str(uuid4()), id2=str(uuid4()), id3=str(uuid4()), id4=str(uuid4()),
        id5=str(uuid4()), id6=str(uuid4()), id7=str(uuid4()), id8=str(uuid4()),
        now=now
    ))
    
    # Seed avatar colors
    avatar_colors_sql = """
    INSERT INTO avatar_colors (id, name, hex_code, rgb, hsl, display_order, is_active, created_at)
    VALUES 
        (:id1, 'Sky Blue', '#7BB7FF', 'rgb(123, 183, 255)', 'hsl(217, 100%, 66%)', 1, true, :now),
        (:id2, 'Sunny Yellow', '#F4D35E', 'rgb(244, 211, 94)', 'hsl(45, 95%, 66%)', 2, true, :now),
        (:id3, 'Mint Green', '#A8DCAB', 'rgb(168, 220, 171)', 'hsl(125, 50%, 76%)', 3, true, :now),
        (:id4, 'Coral Pink', '#F4978E', 'rgb(244, 151, 142)', 'hsl(6, 90%, 76%)', 4, true, :now),
        (:id5, 'Lavender', '#C8A2FF', 'rgb(200, 162, 255)', 'hsl(270, 100%, 74%)', 5, true, :now),
        (:id6, 'Peach', '#FFB37A', 'rgb(255, 179, 122)', 'hsl(20, 100%, 74%)', 6, true, :now),
        (:id7, 'Teal', '#9AD9D2', 'rgb(154, 217, 210)', 'hsl(172, 50%, 73%)', 7, true, :now),
        (:id8, 'Mauve', '#E5A0C9', 'rgb(229, 160, 201)', 'hsl(320, 70%, 76%)', 8, true, :now)
    """
    
    op.execute(text(avatar_colors_sql).bindparams(
        id1=str(uuid4()), id2=str(uuid4()), id3=str(uuid4()), id4=str(uuid4()),
        id5=str(uuid4()), id6=str(uuid4()), id7=str(uuid4()), id8=str(uuid4()),
        now=now
    ))
    
    # Seed tint palette
    tint_palette_sql = """
    INSERT INTO tint_palette (id, name, hsl, hex_code, category, display_order, is_active, created_at)
    VALUES 
        (:id1, 'Linen', '36 55% 70%', '#E8D4C0', 'warm', 1, true, :now),
        (:id2, 'Rust', '14 60% 58%', '#D97060', 'warm', 2, true, :now),
        (:id3, 'Ochre', '38 70% 58%', '#D9A860', 'warm', 3, true, :now),
        (:id4, 'Olive', '70 22% 55%', '#9BA860', 'neutral', 4, true, :now),
        (:id5, 'Sage', '150 18% 58%', '#8FA88A', 'cool', 5, true, :now),
        (:id6, 'Slate', '210 18% 62%', '#8FA0A8', 'cool', 6, true, :now),
        (:id7, 'Plum', '300 18% 60%', '#A88AA0', 'cool', 7, true, :now),
        (:id8, 'Clay', '20 35% 55%', '#C9906B', 'warm', 8, true, :now)
    """
    
    op.execute(text(tint_palette_sql).bindparams(
        id1=str(uuid4()), id2=str(uuid4()), id3=str(uuid4()), id4=str(uuid4()),
        id5=str(uuid4()), id6=str(uuid4()), id7=str(uuid4()), id8=str(uuid4()),
        now=now
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playground_snippets_user_id_created_at', table_name='playground_snippets')
    op.drop_index(op.f('ix_playground_snippets_user_id'), table_name='playground_snippets')
    op.drop_index(op.f('ix_playground_snippets_note_id'), table_name='playground_snippets')
    op.drop_table('playground_snippets')
    op.drop_index('ix_notes_topic_id_created_at', table_name='notes')
    op.drop_index(op.f('ix_notes_topic_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_topics_subject_id_name', table_name='topics')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_status'), table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_materials_subject_id_created_at', table_name='materials')
    op.drop_index(op.f('ix_materials_subject_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_storage_key'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_subjects_user_id_name', table_name='subjects')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_palette_colors_palette_id_display_order', table_name='palette_colors')
    op.drop_index('ix_palette_colors_palette_id', table_name='palette_colors')
    op.drop_table('palette_colors')
    op.drop_index(op.f('ix_tint_palette_is_active'), table_name='tint_palette')
    op.drop_index(op.f('ix_tint_palette_display_order'), table_name='tint_palette')
    op.drop_index(op.f('ix_tint_palette_category'), table_name='tint_palette')
    op.drop_table('tint_palette')
    op.drop_index(op.f('ix_color_palette_is_active'), table_name='color_palette')
    op.drop_table('color_palette')
    op.drop_index(op.f('ix_avatar_styles_slug'), table_name='avatar_styles')
    op.drop_index(op.f('ix_avatar_styles_is_active'), table_name='avatar_styles')
    op.drop_index(op.f('ix_avatar_styles_display_order'), table_name='avatar_styles')
    op.drop_index('ix_avatar_styles_animation_type', table_name='avatar_styles')
    op.drop_table('avatar_styles')
    op.drop_index(op.f('ix_avatar_colors_is_active'), table_name='avatar_colors')
    op.drop_index(op.f('ix_avatar_colors_hex_code'), table_name='avatar_colors')
    op.drop_index(op.f('ix_avatar_colors_display_order'), table_name='avatar_colors')
    op.drop_table('avatar_colors')
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS topicstatus')
    op.execute('DROP TYPE IF EXISTS palettetype')
    # ### end Alembic commands ###
